# Generated by Django 4.1.3 on 2022-12-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Houseinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_num", models.IntegerField(max_length=8)),
                ("house_num", models.IntegerField(max_length=6)),
                ("house_holder", models.CharField(max_length=16)),
            ],
        ),
    ]
