# Generated by Django 4.1.3 on 2022-12-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aptcomplex", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houseinfo",
            name="house_holder",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
