# Generated by Django 3.1.3 on 2022-12-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptcomplex', '0004_auto_20221205_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfo',
            name='house_holder',
        ),
    ]
