# Generated by Django 4.1.3 on 2022-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptcomplex', '0006_houseinfo_house_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
