# Generated by Django 4.1.4 on 2022-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptcomplex', '0008_auto_20221210_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
