# Generated by Django 3.1.3 on 2022-12-05 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20221205_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_building_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_house_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_reg_dt',
        ),
    ]
