# Generated by Django 3.1.3 on 2022-12-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_user_user_building_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_building_num',
            field=models.IntegerField(choices=[(101, '101동'), (102, '102동'), (103, '103동'), (104, '104동'), (105, '105동'), (106, '106동'), (107, '107동')], default='', max_length=8),
        ),
    ]
