# Generated by Django 3.1.3 on 2022-12-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20221205_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_house_num',
            field=models.IntegerField(default=0, max_length=8, verbose_name='호정보'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_building_num',
            field=models.IntegerField(default=0, max_length=16, verbose_name='동정보'),
        ),
    ]
