# Generated by Django 3.1.3 on 2022-12-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptcomplex', '0006_houseinfo_house_holder'),
        ('common', '0008_auto_20221205_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_house_holder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aptcomplex.houseinfo'),
        ),
    ]
