# Generated by Django 3.1.3 on 2022-12-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_user_user_house_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_building_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_house_num',
        ),
    ]
