# Generated by Django 3.1.3 on 2022-12-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20221205_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=128, unique=True, verbose_name='닉네임')),
                ('email', models.EmailField(default='', max_length=128, unique=True, verbose_name='이메일')),
                ('phone_num', models.CharField(default='', max_length=128, verbose_name='전화번호')),
                ('car_num', models.CharField(default='', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
        ),
    ]
