# Generated by Django 4.1.3 on 2022-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_userprofile_car_num_alter_userprofile_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=128, unique=True, verbose_name='이메일'),
        ),
    ]
