# Generated by Django 4.1.3 on 2022-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_num',
            field=models.CharField(default='', max_length=128, verbose_name='전화번호'),
        ),
    ]
