# Generated by Django 3.1.3 on 2022-12-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0010_auto_20221210_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenence',
            fields=[
                ('main_date', models.IntegerField(primary_key=True, serialize=False)),
                ('heatc', models.BigIntegerField(blank=True, null=True)),
                ('heatp', models.BigIntegerField(blank=True, null=True)),
                ('electc', models.BigIntegerField(blank=True, null=True)),
                ('electp', models.BigIntegerField(blank=True, null=True)),
                ('gasc', models.BigIntegerField(blank=True, null=True)),
                ('gasp', models.BigIntegerField(blank=True, null=True)),
                ('waterhotc', models.BigIntegerField(blank=True, null=True)),
                ('waterhotp', models.BigIntegerField(blank=True, null=True)),
                ('watercoolc', models.BigIntegerField(blank=True, null=True)),
                ('watercoolp', models.BigIntegerField(blank=True, null=True)),
                ('domesticwaste', models.BigIntegerField(blank=True, null=True)),
                ('waterpruifier', models.BigIntegerField(blank=True, null=True)),
                ('representation', models.BigIntegerField(blank=True, null=True)),
                ('election', models.BigIntegerField(blank=True, null=True)),
                ('buildingin', models.BigIntegerField(blank=True, null=True)),
                ('House', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.user')),
            ],
            options={
                'db_table': 'maintenence',
            },
        ),
    ]
