# Generated by Django 3.1.3 on 2022-12-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptcomplex', '0008_auto_20221210_1947'),
        ('maintenence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenence',
            name='sum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenence',
            name='House',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aptcomplex.houseinfo'),
        ),
    ]
