# Generated by Django 3.1.3 on 2022-12-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenence', '0005_auto_20221211_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenence',
            name='main_date',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
