# Generated by Django 3.1.3 on 2022-12-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20221210_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
